import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Download, Search, ChevronLeft, ChevronRight, RefreshCw } from 'lucide-react'
import clsx from 'clsx'
import { exportDefectIntake, fetchDefectIntake, fetchDefectIntakeFilterOptions, fetchDefectIntakeSummary } from '../services/api'

const initialFilters = { search: '', module_id: '', import_file_name: '', fixing_status: '', vendor_status: '', date_from: '', date_to: '' }
const badgeStyles = { priority: { Highest: 'bg-pink-50 text-pink-700 border-pink-200', High: 'bg-blue-50 text-blue-700 border-blue-200', Medium: 'bg-amber-50 text-amber-700 border-amber-200', Low: 'bg-slate-100 text-slate-600 border-slate-200' }, fixing: { 'Fix in Progress': 'bg-blue-50 text-blue-700 border-blue-200', 'Ready to Test': 'bg-violet-50 text-violet-700 border-violet-200', 'Needs Attention': 'bg-red-50 text-red-700 border-red-200', 'Critical Action Needed': 'bg-pink-50 text-pink-700 border-pink-200' }, vendor: { 'Done Dev': 'bg-emerald-50 text-emerald-700 border-emerald-200' } }
function Badge({ value, type }) { const label = value || (type === 'workflow' ? 'Open' : 'Belum diisi'); const style = type === 'workflow' ? 'bg-orange-50 text-orange-700 border-orange-200' : badgeStyles[type]?.[label] || 'bg-slate-50 text-slate-500 border-slate-200'; return <span className={clsx('inline-flex px-2 py-1 rounded-full text-[11px] font-semibold border whitespace-nowrap', style)}>{label}</span> }
function Chart({ title, items, total, color }) { const max = Math.max(...(items || []).map(item => item.count), 1); return <div className="card p-4"><div className="flex items-center justify-between mb-4"><h2 className="text-sm font-semibold text-slate-700">{title}</h2><span className="text-[11px] text-slate-400">{total} Open</span></div><div className="space-y-3">{items?.length ? items.map(item => <div key={item.label}><div className="flex justify-between gap-3 text-xs mb-1"><span className="text-slate-600 truncate" title={item.label}>{item.label}</span><strong className="text-slate-700">{item.count}</strong></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className={clsx('h-full rounded-full', color)} style={{ width: `${item.count / max * 100}%` }} /></div></div>) : <p className="text-xs text-slate-400">Tidak ada data.</p>}</div></div> }
function dateText(value) { return value ? new Date(`${value}T00:00:00`).toLocaleDateString('id-ID') : '-' }

export default function DefectIntakePage() {
  const [page, setPage] = useState(1); const [filters, setFilters] = useState(initialFilters)
  const params = { page, page_size: 15, ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value)) }
  const { data, isLoading, isFetching } = useQuery({ queryKey: ['defect-intake', params], queryFn: () => fetchDefectIntake(params), keepPreviousData: true })
  const { data: options } = useQuery({ queryKey: ['defect-intake-options'], queryFn: fetchDefectIntakeFilterOptions })
  const { data: summary } = useQuery({ queryKey: ['defect-intake-summary', params], queryFn: () => fetchDefectIntakeSummary(params) })
  const update = (key, value) => { setFilters(prev => ({ ...prev, [key]: value })); setPage(1) }
  return <div className="space-y-5">
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">Defect Intake</h1><p className="text-sm text-slate-500 mt-1">Defect existing dengan Status Workflow = Open</p></div><button onClick={() => exportDefectIntake(params)} className="flex items-center justify-center px-4 py-2.5 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-sm font-medium"><Download className="w-4 h-4 mr-2" />Export Report Excel</button></div>
    <div className="card p-4"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-7 gap-3"><div className="relative lg:col-span-2"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" /><input value={filters.search} onChange={e => update('search', e.target.value)} placeholder="Cari Defect ID atau Summary" className="w-full pl-9 pr-3 py-2 border border-slate-200 rounded-lg text-sm" /></div><select value={filters.module_id} onChange={e => update('module_id', e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="">Semua Sub-Module</option>{(options?.modules || []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={filters.import_file_name} onChange={e => update('import_file_name', e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="">Semua Nama File Import</option>{(options?.import_files || []).map(item => <option key={item} value={item}>{item}</option>)}</select><select value={filters.fixing_status} onChange={e => update('fixing_status', e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="">Semua Fixing Status</option>{(options?.fixing_statuses || []).map(item => <option key={item} value={item}>{item}</option>)}</select><select value={filters.vendor_status} onChange={e => update('vendor_status', e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm"><option value="">Semua Vendor Status</option>{(options?.vendor_statuses || []).map(item => <option key={item} value={item}>{item}</option>)}</select><button onClick={() => { setFilters(initialFilters); setPage(1) }} className="px-3 py-2 border border-slate-200 rounded-lg text-sm text-slate-600 hover:bg-slate-50"><RefreshCw className="w-4 h-4 inline mr-1" />Reset</button></div><div className="flex flex-wrap items-center gap-2 mt-3"><span className="text-xs font-semibold text-slate-500">Tanggal dibuat:</span><input type="date" value={filters.date_from} onChange={e => update('date_from', e.target.value)} className="px-2 py-1.5 border border-slate-200 rounded text-xs" /><span className="text-xs text-slate-400">s/d</span><input type="date" value={filters.date_to} onChange={e => update('date_to', e.target.value)} className="px-2 py-1.5 border border-slate-200 rounded text-xs" /></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><Chart title="Priority of Defect Fixing" items={summary?.priority} total={summary?.total || 0} color="bg-blue-400" /><Chart title="Fixing / Review Status" items={summary?.fixing_review} total={summary?.total || 0} color="bg-violet-400" /><Chart title="Vendor Status" items={summary?.vendor} total={summary?.total || 0} color="bg-emerald-400" /></div>
    <div className="card overflow-hidden"><div className="px-5 py-4 border-b border-slate-100 flex justify-between"><p className="text-sm font-semibold text-slate-700">{data?.total || 0} defect Open</p>{isFetching && <span className="text-xs text-slate-400">Memuat...</span>}</div><div className="overflow-x-auto"><table className="w-full text-xs min-w-[1500px]"><thead><tr className="bg-slate-50 border-b border-slate-200 text-left text-slate-500"><th className="px-4 py-3">Defect ID</th><th className="px-4 py-3">Nama File Import</th><th className="px-4 py-3">Modul (Sub-Module)</th><th className="px-4 py-3">Sheet Name</th><th className="px-4 py-3 min-w-[260px]">Summary</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Status Workflow</th><th className="px-4 py-3">Date Created</th><th className="px-4 py-3">Fixing / Review</th><th className="px-4 py-3">Vendor Status</th><th className="px-4 py-3 min-w-[220px]">Keterangan</th><th className="px-4 py-3 min-w-[220px]">Note</th></tr></thead><tbody>{isLoading ? <tr><td colSpan="12" className="p-8 text-center text-slate-400">Memuat data...</td></tr> : data?.items?.length ? data.items.map(item => <tr key={item.defect_id} className="border-b border-slate-100 align-top hover:bg-slate-50"><td className="px-4 py-3 font-semibold text-primary-700">{item.defect_id}</td><td className="px-4 py-3">{item.import_file_name || '-'}</td><td className="px-4 py-3">{item.module_name || '-'}</td><td className="px-4 py-3">{item.sheet_name || '-'}</td><td className="px-4 py-3 whitespace-normal">{item.summary || '-'}</td><td className="px-4 py-3"><Badge value={item.priority} type="priority" /></td><td className="px-4 py-3"><Badge value={item.status} type="workflow" /></td><td className="px-4 py-3 whitespace-nowrap">{dateText(item.date_created)}</td><td className="px-4 py-3"><Badge value={item.fixing_review_status} type="fixing" /></td><td className="px-4 py-3"><Badge value={item.fixing_status_by_vendor} type="vendor" /></td><td className="px-4 py-3 whitespace-pre-wrap">{item.keterangan || '-'}</td><td className="px-4 py-3 whitespace-pre-wrap">{item.note || '-'}</td></tr>) : <tr><td colSpan="12" className="p-8 text-center text-slate-400">Tidak ada defect Open.</td></tr>}</tbody></table></div><div className="px-5 py-3 border-t border-slate-100 flex items-center justify-between"><span className="text-xs text-slate-500">Halaman {data?.page || 1} dari {data?.total_pages || 1}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="p-1.5 rounded border text-slate-600 disabled:text-slate-300"><ChevronLeft className="w-4 h-4" /></button><button disabled={page >= (data?.total_pages || 1)} onClick={() => setPage(value => value + 1)} className="p-1.5 rounded border text-slate-600 disabled:text-slate-300"><ChevronRight className="w-4 h-4" /></button></div></div></div>
  </div>
}
